<a href="https://colab.research.google.com/github/honeylouluzon/Guided-Project-AI-ML-DataScience/blob/main/Deep_Learning_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Needed imports
import numpy as np
import tensorflow as tf
print(tf.__version__)


2.19.0


In [ ]:
#Creating the Input Layer
age = 34
experience = 7
input_layer = np.array([age, experience])
print(input_layer)


[34  7]


#Neural Network with 1 hidden layer

In [ ]:
#Creating the weights
weights_topnode = np.array([2,1])
weights_bottomnode = np.array([-2,-5])
output_weights = np.array([3,-1])
print(weights_topnode)
print(weights_bottomnode)
print(output_weights)


[2 1]
[-2 -5]
[ 3 -1]


In [ ]:
#Calculating the Hidden Layer
top_node_value = (input_layer * weights_topnode).sum()
bottom_node_value = (input_layer * weights_bottomnode).sum()
print(top_node_value)
print(bottom_node_value)


75
-103


In [ ]:
#Creating the Hidden Layer
hidden_layer_values = np.array([top_node_value, bottom_node_value])
print(hidden_layer_values)


[  75 -103]


In [ ]:
#Calculating the Prediction Layer
prediction = (hidden_layer_values * output_weights).sum()
print(prediction)


328


#Neural Network with 2 hidden layer with relu activation

In [ ]:
def relu(x):
  y=max(0,x)
  return y


In [ ]:
#Set first layer weights
weights_node_1 = np.array([2,1])
weights_node_2 = np.array([-2,-5])


In [ ]:
#Calculate first hidden layer with relu
n1 = (input_layer * weights_node_1).sum()
n2 = (input_layer * weights_node_2).sum()
n1_output = relu(n1)
n2_output = relu(n2)
layer_1_output = np.array([n1_output,n2_output])
print(layer_1_output)



[75  0]


In [ ]:
#Set second layer weights
weights_node_3 = np.array([3,1])
weights_node_4 = np.array([-1,-2])



In [ ]:
#Calculate second hidden layer with relu
n3 = (layer_1_output * weights_node_3).sum()
n4 = (layer_1_output * weights_node_4).sum()
n3_output = relu(n3)
n4_output = relu(n4)
layer_2_output = np.array([n3_output,n4_output])
print(layer_2_output)



[225   0]


In [ ]:
#Set output weights
output_weights = np.array([2,-6])



In [ ]:
#Calculate prediction
prediction = relu((layer_2_output * output_weights).sum())
print(prediction)



450


#Tensor Flow

In [ ]:
#Create tensor with 1 value only
t0 = tf.ones((3,))
print(t0)


tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [ ]:
t1 = tf.ones((1,3))
print(t1)


tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)


In [ ]:
#Create tensor with range value
t2 = tf.range(start=1, limit=15, delta=2)
print(t2)


tf.Tensor([ 1  3  5  7  9 11 13], shape=(7,), dtype=int32)


In [ ]:
#Exercise
x1 = tf.ones((1,7))
x2 = tf.zeros((1,3))
x3 = tf.range(start=21, limit=30, delta=2)



In [ ]:
#Print Exercise
print(x1)
print(x2)
print(x3)

tf.Tensor([[1. 1. 1. 1. 1. 1. 1.]], shape=(1, 7), dtype=float32)
tf.Tensor([[0. 0. 0.]], shape=(1, 3), dtype=float32)
tf.Tensor([21 23 25 27 29], shape=(5,), dtype=int32)


In [ ]:
#Create constant tensor
c1 = tf.constant([1, 2, 3, 4, 5, 6])
print(c1)


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
c2 = tf.constant([[100, 200, 300], [400, 500, 600]])
print(c2)



tf.Tensor(
[[100 200 300]
 [400 500 600]], shape=(2, 3), dtype=int32)


In [ ]:
#Create tensor with 2 value only using ones
c3 = tf.ones((2,3))*2
print(c3)

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)


In [ ]:
#Create 3x3 tensor with diagonal 1
c4 = tf.eye(3)
print(c4)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
#Change the data type of a tensor
c5 = tf.cast(c2, dtype=tf.float32)
print(c5)

tf.Tensor(
[[100. 200. 300.]
 [400. 500. 600.]], shape=(2, 3), dtype=float32)


In [ ]:
#Create variable for tensor
v1 = tf.Variable([1, 2, 3, 4, 5, 6])
print(v1)

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>


In [ ]:
#Assign new variable to tensor
v1.assign(value=[7,8,9,10,11,12])
print(v1)



<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([ 7,  8,  9, 10, 11, 12], dtype=int32)>


In [ ]:
v2 = tf.Variable(['True','True','False','False'])
print(v2)


<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'True', b'True', b'False', b'False'], dtype=object)>


In [ ]:
v3 = tf.Variable([[20,25],[22,16]])
print(v3)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[20, 25],
       [22, 16]], dtype=int32)>


In [ ]:
v3.assign(value=[[15,20],[12,16]])
print(v3)



<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[15, 20],
       [12, 16]], dtype=int32)>


In [ ]:
#Convert tensor to numpy array
v3_array = v3.numpy()
print(v3_array)

[[15 20]
 [12 16]]


In [ ]:
#Other way to convert tensor to numpy array
v3_array2 = np.array(v3)
print(v3_array2)

[[15 20]
 [12 16]]


In [ ]:
#Convert array to tensor
v3_tensor = tf.convert_to_tensor(v3_array)
print(v3_tensor)

tf.Tensor(
[[15 20]
 [12 16]], shape=(2, 2), dtype=int32)


In [ ]:
n1 = tf.Variable([[10,15],[20,25]])
print(n1)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 15],
       [20, 25]], dtype=int32)>


In [ ]:
array1 = n1.numpy()
print(array1)

[[10 15]
 [20 25]]


In [ ]:
array2 = np.array(n1)
print(array2)

[[10 15]
 [20 25]]


In [ ]:
nt1 = tf.convert_to_tensor(array2)
print(nt1)

tf.Tensor(
[[10 15]
 [20 25]], shape=(2, 2), dtype=int32)


In [ ]:
#Exercise initialization
t1 = tf.constant([6, 4, 10])
t2 = tf.constant([3, 2, 4])
t3 = tf.Variable([[20, 25], [22, 16]])
t4 = tf.Variable([[10, 5], [11, 8]])

In [ ]:
#Tensor sum function
op1 = tf.add(t1,t2)
print(op1)

tf.Tensor([ 9  6 14], shape=(3,), dtype=int32)


In [ ]:
#Tensor subrtact function
op2 = tf.subtract(t3,t4)
print(op2)

tf.Tensor(
[[10 20]
 [11  8]], shape=(2, 2), dtype=int32)


In [ ]:
#Tensor product function
op3 = tf.multiply(t1,t2)
print(op3)

tf.Tensor([18  8 40], shape=(3,), dtype=int32)


In [ ]:
#Tensor divide function
op4 = tf.divide(t3,t4)
print(op4)

tf.Tensor(
[[2. 5.]
 [2. 2.]], shape=(2, 2), dtype=float64)


In [ ]:
#Error - do not have same shape
t1 = tf.constant([0, 5, 11])
t2 = tf.constant([2, 9])

ex1 = tf.add(t1, t2)
print(ex1)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [2] [Op:AddV2] name: 

In [ ]:
#Broadcasting (stretch the smaller value to have same shape with other tensor)
t3 = tf.constant([0, 5, 11])
t4 = tf.constant([2])

ex2 = tf.add(t3, t4)
print(ex2)

tf.Tensor([ 2  7 13], shape=(3,), dtype=int32)


In [ ]:
#Exercise initialization
t5 = tf.constant([[2, 0], [3, 0], [1, 5], [0, 4]])
t6 = tf.constant([[3, 5], [8, 13]])
t7 = tf.constant([[1], [1], [4], [2]])

In [ ]:
#Print shape
print(t5.shape)
print(t6.shape)
print(t7.shape)


(4, 2)
(2, 2)
(4, 1)


In [ ]:
#Adding tensor with broadcasting non similar shape
op5 = tf.add(t5,t7)
print(op5)

tf.Tensor(
[[3 1]
 [4 1]
 [5 9]
 [2 6]], shape=(4, 2), dtype=int32)


##Tensor Advance Math

In [ ]:
#Advance mathematical
x = tf.constant([-2.25, -48.23, 6.25])
print(tf.math.abs(x))

tf.Tensor([ 2.25 48.23  6.25], shape=(3,), dtype=float32)


In [ ]:
#Exercise initialization
t1 = tf.constant([6, 4, 10])
t2 = tf.constant([3, 2, 4])

t3 = tf.Variable([[2.4, 2.5], [2.2, 1.6]])
t4 = tf.Variable([[9, 5], [16, 8]])

t_log = []
t_cumsum = []
t_tanh = []
t_sqrt = []

In [ ]:
def tensor_log(t,n):
  log = tf.math.log(tf.cast(t,tf.float32))
  t_log.append(f'{n} | {log}')

def tensor_cumsum(t, n):
  cumsum = tf.math.cumsum(t)
  t_cumsum.append(f'{n} | {cumsum}')

def tensor_tanh(t, n):
  tanh = tf.math.tanh(t)
  t_tanh.append(f'{n} | {tanh}')

def tensor_sqrt(t, n):
  sqrt = tf.math.sqrt(tf.cast(t,tf.float32))
  t_sqrt.append(f'{n} | {sqrt}')

In [ ]:
#Log a tensor
tensor_log(t1,"t1")

In [ ]:
#Print latest log
if len(t_log)!=0:
  print(t_log[-1])
else:
  print("No Log")

t1 | [1.7917595 1.3862944 2.3025851]


In [ ]:
#Print all logs
for index, item in enumerate(t_log):
  print(f'[{index}] {item}')

[0] t1 | [1.7917595 1.3862944 2.3025851]


In [ ]:
#Cumsum a tensor
tensor_cumsum(t2,"t2")

In [ ]:
#Print latest cumsum
if len(t_cumsum)!=0:
  print(t_cumsum[-1])
else:
  print("No cumsum")

t2 | [3 5 9]


In [ ]:
#Print all cumsum
for index, item in enumerate(t_cumsum):
  print(f'[{index}] {item}')

[0] t2 | [3 5 9]


In [ ]:
#Tahn a tensor
tensor_tanh(t3,"t3")


In [ ]:
#Print latest tanh
if len(t_tanh)!=0:
  print(t_tanh[-1])
else:
  print("No tahn")


t3 | [[0.98367494 0.9866143 ]
 [0.97574323 0.9216685 ]]


In [ ]:
#Print all tanh
for index, item in enumerate(t_tanh):
  print(f'[{index}] {item}')


[0] t3 | [[0.98367494 0.9866143 ]
 [0.97574323 0.9216685 ]]
[1] t3 | [[0.98367494 0.9866143 ]
 [0.97574323 0.9216685 ]]


In [ ]:
#Sqrt a tensor
tensor_sqrt(t4,"t4")


In [ ]:
#Print latest sqrt
if len(t_sqrt)!=0:
  print(t_sqrt[-1])
else:
  print("No sqrt")


t4 | [[3.       2.236068]
 [4.       2.828427]]


In [ ]:
#Print all sqrt
for index, item in enumerate(t_sqrt):
  print(f'[{index}] {item}')


[0] t4 | [[3.       2.236068]
 [4.       2.828427]]
